-- 02-enums.sql
CREATE TYPE "Role" AS ENUM ('STUDENT', 'FACULTY', 'ADMIN');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LATE');
CREATE TYPE "SubmissionStatus" AS ENUM ('SUBMITTED', 'GRADED');
CREATE TYPE "ExamStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ResultStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "AnnouncementType" AS ENUM ('GENERAL', 'ACADEMIC', 'EVENT', 'EXAM', 'URGENT');
CREATE TYPE "NotificationType" AS ENUM ('GENERAL', 'ACADEMIC', 'EVENT', 'EXAM', 'SYSTEM');
